version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker/worker.py
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest tests/
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - redis
